### ISSUE TITLE
C compiler checks octal literals during preprocessing?

### ISSUE THREAD

**Issue by NovaRain** [open-watcom/open-watcom-v2#595]
The SSL scripts of cRPG Fallout 2 require a C preprocessor for its script compiler to work.
The same script line `GOption(146, Node010c, 008);` didn't produce any error before (official 1.9 or older beta from 2017), but now WCC gives `Error! E1163: Invalid octal constant` message for the "008". Is this check for octal literals during preprocessing intended? Because using some other C compilers (e.g. GCC, Embarcadero, Orange C) to preprocess the script doesn't give any warning/error about octal either.

**Comment by jmalak** [comment]
It looks like mistake, C preprocessor code is shared by other OW tools that some check was included in wrong place. I will review it.

**Comment by jmalak** [comment]
you can use as workaround wcpp utility (standalone C preprocessor).

**Comment by jmalak** [comment]
it is also problem with C++ compiler.

**Comment by jmalak** [comment]
Please what compiler command line you use?

**Comment by NovaRain** [comment]
> 
> 
> Please what compiler command line you use?

I use these command line options to preprocess scripts:
`wcc386.exe myscript.ssl -p -fo=myscript.tmp.ssl -w4`

**Comment by jmalak** [comment]
It is related to the change in compilers error handling.
OW 1.9 and older versions has simply suppresed any messages during preprocessing.
OW 2.0 has enabled messages during preprocessing to show necessary messages and now it show mistakes in compilers that translation phase 6 and 7 is processed for some tokens even if compilers should not do this. I will review code and fix it.

**Comment by jmalak** [comment]
I fixed compiler preprocessing mode to not process translating phases unnecessary for preprocessing. It suppress unwanted messages.
It was changed against previous version OW to enable display errors during preprocessing.
Original solution was stupid; to suppress "all" messages/errors if in preproccessing mode.

**Comment by NovaRain** [comment]
I tested the current release (12e1f32) and it seems working well again. Thanks for the fix.

**Comment by NovaRain** [comment]
Sorry for reopening the issue, but I just found out that the error message pops out again after updating wcc386.
I tried some older builds, and the error reoccurs starting from 2021-01-01 build.

**Comment by jmalak** [comment]
Please, could you give me reference to code which exhibits the problem.

**Comment by NovaRain** [comment]
> Please, could you give me reference to code which exhibits the problem.

You mean the script code? It's still the same as my first post, some lines which use "008" or "009", For example:
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/f99d771ea34f953c4b0c99ae65116728d2439d90/scripts_src/den/dcmetzge.ssl#L760

**Comment by jmalak** [comment]
Thanks, I will fix it ASAP.

**Comment by NovaRain** [comment]
> Thanks, I will fix it ASAP.

Hi. Just curious if this is still being looked into. While I can use wpp386 for preprocessing instead, I'd like to use wcc386 as the document from original developers said if possible.

**Comment by jmalak** [comment]
I have it on my task list, but with lower priority.
I thing it is related to complete rework of pre-processor arithmetic to be C99 compliant.
